[package]
name = "uefi-app"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["disk_image"]

[dependencies]
log = "0.4.21"
uefi = { version = "0.28.0", features = ["panic_handler", "logger"] }
